[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dd-core"
version = "1.0"
authors = [
    {name = "Dr. Janis Meyer"}
]
description = "Core data structures, dataflows, mappers and utilities for deepdoctection"
readme = "README.md"
license = {text = "Apache License 2.0"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "catalogue==2.0.10",
    "lazy-imports==0.3.1",
    "numpy>2.0",
    "packaging>=20.0",
    "Pillow>=10.0.0",
    "pydantic>=2.0",
    "pydantic-settings",
    "pyyaml>=6.0.1",
    "termcolor>=1.1",
    "tabulate>=0.7.7",
    "tqdm>=4.64.0",
]

[project.optional-dependencies]
full = [
    "pypdf>=6.0.0",
    "jsonlines==3.1.0",
    "scipy>=1.13.1",
    "pypdfium2>=4.30.0,<5.0"
]

types = [
    "mypy==1.18.2",
    "types-PyYAML>=6.0.12.12",
    "types-termcolor>=1.1.3",
    "types-tabulate>=0.9.0.3",
    "types-tqdm>=4.66.0.5",
    "types-Pillow>=10.2.0.20240406",
    "types-urllib3>=1.26.25.14",
]

dev = [
    "black==25.11.0",
    "isort==7.0.0",
    "pylint==4.0.2",
]

test = [
    "hypothesis",
    "pytest==9.0.1",
    "pytest-cov==7.0.0",
]

[project.urls]
Homepage = "https://github.com/deepdoctection/deepdoctection"
Documentation = "https://deepdoctection.readthedocs.io"
Repository = "https://github.com/deepdoctection/deepdoctection"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dd_datapoint = ["py.typed"]
