name: style

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [master]

jobs:
  analyze:
    if: "(contains(github.event.head_commit.message, '[force ci]') || github.ref == 'refs/heads/master' || github.event_name == 'pull_request') && !contains(github.event.head_commit.message, '[skip test]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]
        pip: [25.3]
        tox: [4.32.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install tox
        run: |
          python -m pip install --upgrade pip==${{ matrix.pip }}
          pip install tox==${{ matrix.tox }}

      - name: Run analyze
        run: make analyze

  check-lint-and-format:
    if: "(contains(github.event.head_commit.message, '[force ci]') || github.ref == 'refs/heads/master' || github.event_name == 'pull_request') && !contains(github.event.head_commit.message, '[skip test]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]
        pip: [25.3]
        tox: [4.32.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install tox
        run: |
          python -m pip install --upgrade pip==${{ matrix.pip }}
          pip install tox==${{ matrix.tox }}

      - name: Run check-lint-and-format
        run: make check-lint-and-format
